<?xml version="1.0" encoding="UTF-8"?>
<ticket>
  <assigned-user-id type="integer">1366</assigned-user-id>
  <attachments-count type="integer">2</attachments-count>
  <closed type="boolean">true</closed>
  <created-at type="datetime">2009-01-07T17:00:37+00:00</created-at>
  <creator-id type="integer">32378</creator-id>
  <milestone-due-on type="datetime" nil="true"></milestone-due-on>
  <milestone-id type="integer">9903</milestone-id>
  <number type="integer">1708</number>
  <permalink>fixtures-starting-with-test_-will-break-unit-tests</permalink>
  <priority type="integer">1021</priority>
  <project-id type="integer">8994</project-id>
  <raw-data type="binary" nil="true" encoding="base64"></raw-data>
  <state>invalid</state>
  <tag>2.3.2 activerecord fixtures patch test testing tests unit</tag>
  <title>Fixtures starting with &quot;test_&quot; run redundant unit tests</title>
  <updated-at type="datetime">2009-08-08T14:53:51+01:00</updated-at>
  <user-id type="integer">19965</user-id>
  <version type="integer">9</version>
  <user-name>Jos&#233; Valim</user-name>
  <creator-name>hukl</creator-name>
  <assigned-user-name>Pratik</assigned-user-name>
  <url>http://rails.lighthouseapp.com/projects/8994/tickets/1708</url>
  <milestone-title>2.x</milestone-title>
  <priority-name nil="true"></priority-name>
  <original-body>Rails 2.2.2

When you create an empty app and generate a model called TestFoo you get a fixture file called test_foos.yml.

Now when you run the test you get a pretty wild exception from deep down. When you remove that fixture file, everything runs smoothly. We tried several variations of the naming and it really seems only to occur with the &quot;test_&quot; prefix.

This should be handled more gracefully, or even better, get fixed!

I attached a sample rails app with really only the bare minimum of files and a sqlite3 db.

The Exception you should get goes like this:  

  1) Error:
test_foos(ActionController::TestCase):
ArgumentError: wrong number of arguments (0 for 1)
    /opt/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/test_case.rb:134:in `initialize'
    /opt/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/test_case.rb:134:in `new'
    /opt/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/test_case.rb:134:in `setup_controller_request_and_response'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:178:in `send'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:178:in `evaluate_method'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:166:in `call'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:90:in `run'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:90:in `each'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:90:in `send'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:90:in `run'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:277:in `run_callbacks'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/testing/setup_and_teardown.rb:58:in `run'</original-body>
  <latest-body>Rails 2.2.2

When you create an empty app and generate a model called TestFoo you get a fixture file called test_foos.yml.

Now when you run the test you get a pretty wild exception from deep down. When you remove that fixture file, everything runs smoothly. We tried several variations of the naming and it really seems only to occur with the &quot;test_&quot; prefix.

This should be handled more gracefully, or even better, get fixed!

I attached a sample rails app with really only the bare minimum of files and a sqlite3 db.

The Exception you should get goes like this:  

  1) Error:
test_foos(ActionController::TestCase):
ArgumentError: wrong number of arguments (0 for 1)
    /opt/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/test_case.rb:134:in `initialize'
    /opt/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/test_case.rb:134:in `new'
    /opt/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/test_case.rb:134:in `setup_controller_request_and_response'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:178:in `send'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:178:in `evaluate_method'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:166:in `call'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:90:in `run'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:90:in `each'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:90:in `send'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:90:in `run'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:277:in `run_callbacks'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/testing/setup_and_teardown.rb:58:in `run'</latest-body>
  <original-body-html>&lt;div&gt;&lt;p&gt;Rails 2.2.2&lt;/p&gt;
&lt;p&gt;When you create an empty app and generate a model called TestFoo
you get a fixture file called test_foos.yml.&lt;/p&gt;
&lt;p&gt;Now when you run the test you get a pretty wild exception from
deep down. When you remove that fixture file, everything runs
smoothly. We tried several variations of the naming and it really
seems only to occur with the &quot;test_&quot; prefix.&lt;/p&gt;
&lt;p&gt;This should be handled more gracefully, or even better, get
fixed!&lt;/p&gt;
&lt;p&gt;I attached a sample rails app with really only the bare minimum
of files and a sqlite3 db.&lt;/p&gt;
&lt;p&gt;The Exception you should get goes like this:&lt;br&gt;&lt;/p&gt;
&lt;p&gt;1) Error: test_foos(ActionController::TestCase): ArgumentError:
wrong number of arguments (0 for 1)&lt;/p&gt;
&lt;pre&gt;
&lt;code&gt;/opt/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/test_case.rb:134:in `initialize'
/opt/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/test_case.rb:134:in `new'
/opt/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/test_case.rb:134:in `setup_controller_request_and_response'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:178:in `send'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:178:in `evaluate_method'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:166:in `call'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:90:in `run'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:90:in `each'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:90:in `send'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:90:in `run'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:277:in `run_callbacks'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/testing/setup_and_teardown.rb:58:in `run'
&lt;/code&gt;
&lt;/pre&gt;&lt;/div&gt;</original-body-html>
  <versions type="array">
    <version type="Ticket::Version">
      <assigned-user-id type="integer" nil="true"></assigned-user-id>
      <attachments-count type="integer">0</attachments-count>
      <body>Rails 2.2.2

When you create an empty app and generate a model called TestFoo you get a fixture file called test_foos.yml.

Now when you run the test you get a pretty wild exception from deep down. When you remove that fixture file, everything runs smoothly. We tried several variations of the naming and it really seems only to occur with the &quot;test_&quot; prefix.

This should be handled more gracefully, or even better, get fixed!

I attached a sample rails app with really only the bare minimum of files and a sqlite3 db. Run rake test:units to get the exception.

The Exception you should get goes like this:  

  1) Error:
test_foos(ActionController::TestCase):
ArgumentError: wrong number of arguments (0 for 1)
    /opt/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/test_case.rb:134:in `initialize'
    /opt/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/test_case.rb:134:in `new'
    /opt/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/test_case.rb:134:in `setup_controller_request_and_response'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:178:in `send'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:178:in `evaluate_method'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:166:in `call'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:90:in `run'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:90:in `each'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:90:in `send'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:90:in `run'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:277:in `run_callbacks'
    /opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/testing/setup_and_teardown.rb:58:in `run'</body>
      <body-html>&lt;div&gt;&lt;p&gt;Rails 2.2.2&lt;/p&gt;
&lt;p&gt;When you create an empty app and generate a model called TestFoo
you get a fixture file called test_foos.yml.&lt;/p&gt;
&lt;p&gt;Now when you run the test you get a pretty wild exception from
deep down. When you remove that fixture file, everything runs
smoothly. We tried several variations of the naming and it really
seems only to occur with the &quot;test_&quot; prefix.&lt;/p&gt;
&lt;p&gt;This should be handled more gracefully, or even better, get
fixed!&lt;/p&gt;
&lt;p&gt;I attached a sample rails app with really only the bare minimum
of files and a sqlite3 db. Run rake test:units to get the
exception.&lt;/p&gt;
&lt;p&gt;The Exception you should get goes like this:&lt;br&gt;&lt;/p&gt;
&lt;p&gt;1) Error: test_foos(ActionController::TestCase): ArgumentError:
wrong number of arguments (0 for 1)&lt;/p&gt;
&lt;pre&gt;
&lt;code&gt;/opt/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/test_case.rb:134:in `initialize'
/opt/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/test_case.rb:134:in `new'
/opt/local/lib/ruby/gems/1.8/gems/actionpack-2.2.2/lib/action_controller/test_case.rb:134:in `setup_controller_request_and_response'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:178:in `send'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:178:in `evaluate_method'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:166:in `call'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:90:in `run'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:90:in `each'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:90:in `send'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:90:in `run'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/callbacks.rb:277:in `run_callbacks'
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.2.2/lib/active_support/testing/setup_and_teardown.rb:58:in `run'
&lt;/code&gt;
&lt;/pre&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">false</closed>
      <created-at type="datetime">2009-01-07T17:00:38+00:00</created-at>
      <creator-id type="integer">32378</creator-id>
      <diffable-attributes type="yaml">--- {}

</diffable-attributes>
      <milestone-id type="integer">9903</milestone-id>
      <number type="integer">1708</number>
      <permalink>fixtures-starting-with-test_-will-break-unit-tests</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>new</state>
      <tag>2.2.2 actioncontroller exceptions fixtures test testing tests unit</tag>
      <title>Fixtures starting with &quot;test_&quot; will break unit tests</title>
      <updated-at type="datetime">2009-01-07T17:04:10+00:00</updated-at>
      <user-id type="integer">32378</user-id>
      <version type="integer">1</version>
      <user-name>hukl</user-name>
      <creator-name>hukl</creator-name>
      <assigned-user-name nil="true"></assigned-user-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/1708</url>
      <milestone-title>2.x</milestone-title>
      <priority-name nil="true"></priority-name>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer">1366</assigned-user-id>
      <attachments-count type="integer">1</attachments-count>
      <body>I tried and it works fine for me. Could you please attach a patch or a failing test ?

Thanks.</body>
      <body-html>&lt;div&gt;&lt;p&gt;I tried and it works fine for me. Could you please attach a
patch or a failing test ?&lt;/p&gt;
&lt;p&gt;Thanks.&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">true</closed>
      <created-at type="datetime">2009-03-08T00:17:14+00:00</created-at>
      <creator-id type="integer">32378</creator-id>
      <diffable-attributes type="yaml">--- 
:state: new
:assigned_user: 
</diffable-attributes>
      <milestone-id type="integer">9903</milestone-id>
      <number type="integer">1708</number>
      <permalink>fixtures-starting-with-test_-will-break-unit-tests</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>invalid</state>
      <tag>2.2.2 actioncontroller exceptions fixtures test testing tests unit</tag>
      <title>Fixtures starting with &quot;test_&quot; will break unit tests</title>
      <updated-at type="datetime">2009-03-08T00:17:17+00:00</updated-at>
      <user-id type="integer">1366</user-id>
      <version type="integer">2</version>
      <user-name>Pratik</user-name>
      <creator-name>hukl</creator-name>
      <assigned-user-name>Pratik</assigned-user-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/1708</url>
      <milestone-title>2.x</milestone-title>
      <priority-name nil="true"></priority-name>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer">1366</assigned-user-id>
      <attachments-count type="integer">1</attachments-count>
      <body>The attached sample app worked for you ? I just downloaded it again and I still got the same exception. This is odd. A co worker of mine tried it on his linux getting the same problem. He even blogged about it:

http://tech.artcom.de/blog/?p=211

I really don't know what else to provide. Any ideas how to trace it?</body>
      <body-html>&lt;div&gt;&lt;p&gt;The attached sample app worked for you ? I just downloaded it
again and I still got the same exception. This is odd. A co worker
of mine tried it on his linux getting the same problem. He even
blogged about it:&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;http://tech.artcom.de/blog/?p=211&quot;&gt;http://tech.artcom.de/blog/?p=211&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;I really don't know what else to provide. Any ideas how to trace
it?&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">true</closed>
      <created-at type="datetime">2009-03-08T02:42:40+00:00</created-at>
      <creator-id type="integer">32378</creator-id>
      <diffable-attributes type="yaml">--- {}

</diffable-attributes>
      <milestone-id type="integer">9903</milestone-id>
      <number type="integer">1708</number>
      <permalink>fixtures-starting-with-test_-will-break-unit-tests</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>invalid</state>
      <tag>2.2.2 actioncontroller exceptions fixtures test testing tests unit</tag>
      <title>Fixtures starting with &quot;test_&quot; will break unit tests</title>
      <updated-at type="datetime">2009-03-08T02:42:44+00:00</updated-at>
      <user-id type="integer">32378</user-id>
      <version type="integer">3</version>
      <user-name>hukl</user-name>
      <creator-name>hukl</creator-name>
      <assigned-user-name>Pratik</assigned-user-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/1708</url>
      <milestone-title>2.x</milestone-title>
      <priority-name nil="true"></priority-name>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer">1366</assigned-user-id>
      <attachments-count type="integer">1</attachments-count>
      <body>Nop, I generated a new Rails app from the edge and added a model called test_foo and tests/fixtures for it. It all worked.

Thanks!</body>
      <body-html>&lt;div&gt;&lt;p&gt;Nop, I generated a new Rails app from the edge and added a model
called test_foo and tests/fixtures for it. It all worked.&lt;/p&gt;
&lt;p&gt;Thanks!&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">true</closed>
      <created-at type="datetime">2009-03-08T13:39:00+00:00</created-at>
      <creator-id type="integer">32378</creator-id>
      <diffable-attributes type="yaml">--- {}

</diffable-attributes>
      <milestone-id type="integer">9903</milestone-id>
      <number type="integer">1708</number>
      <permalink>fixtures-starting-with-test_-will-break-unit-tests</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>invalid</state>
      <tag>2.2.2 actioncontroller exceptions fixtures test testing tests unit</tag>
      <title>Fixtures starting with &quot;test_&quot; will break unit tests</title>
      <updated-at type="datetime">2009-03-08T13:39:06+00:00</updated-at>
      <user-id type="integer">1366</user-id>
      <version type="integer">4</version>
      <user-name>Pratik</user-name>
      <creator-name>hukl</creator-name>
      <assigned-user-name>Pratik</assigned-user-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/1708</url>
      <milestone-title>2.x</milestone-title>
      <priority-name nil="true"></priority-name>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer">1366</assigned-user-id>
      <attachments-count type="integer">1</attachments-count>
      <body>Alright, its a rails 2.2.2 Problem then. 

I just tried it with Edge/2.3 and its working indeed. Can be set to resolved then.

Thank you for looking at it!</body>
      <body-html>&lt;div&gt;&lt;p&gt;Alright, its a rails 2.2.2 Problem then.&lt;/p&gt;
&lt;p&gt;I just tried it with Edge/2.3 and its working indeed. Can be set
to resolved then.&lt;/p&gt;
&lt;p&gt;Thank you for looking at it!&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">true</closed>
      <created-at type="datetime">2009-03-08T16:49:29+00:00</created-at>
      <creator-id type="integer">32378</creator-id>
      <diffable-attributes type="yaml">--- {}

</diffable-attributes>
      <milestone-id type="integer">9903</milestone-id>
      <number type="integer">1708</number>
      <permalink>fixtures-starting-with-test_-will-break-unit-tests</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>invalid</state>
      <tag>2.2.2 actioncontroller exceptions fixtures test testing tests unit</tag>
      <title>Fixtures starting with &quot;test_&quot; will break unit tests</title>
      <updated-at type="datetime">2009-03-08T16:49:34+00:00</updated-at>
      <user-id type="integer">32378</user-id>
      <version type="integer">5</version>
      <user-name>hukl</user-name>
      <creator-name>hukl</creator-name>
      <assigned-user-name>Pratik</assigned-user-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/1708</url>
      <milestone-title>2.x</milestone-title>
      <priority-name nil="true"></priority-name>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer">1366</assigned-user-id>
      <attachments-count type="integer">1</attachments-count>
      <body>Hmm, test works, but redundant test cases appear out of nowhere.
I hit this with TestResult, and found this ticket.

@@@
$ rake test:units
(in /tmp/foo)
/usr/bin/ruby1.8 -I&quot;lib:test&quot; &quot;/home/nov/gems/gems/rake-0.8.7/lib/rake/rake_test_loader.rb&quot; &quot;test/unit/test_foo_test.rb&quot; 
Loaded suite /home/nov/gems/gems/rake-0.8.7/lib/rake/rake_test_loader
Started
........
Finished in 0.057495 seconds.

8 tests, 1 assertions, 0 failures, 0 errors
^^^^^^^
$ ruby -I test test/unit/test_foo_test.rb -v
Loaded suite test/unit/test_foo_test
Started
test_foos(ActionController::IntegrationTest): .
test_foos(ActionController::TestCase): .
test_foos(ActionMailer::TestCase): .
test_foos(ActionView::TestCase): .
test_foos(ActiveRecord::TestCase): .
test_foos(ActiveSupport::TestCase): .
test_foos(TestFooTest): .
test_the_truth(TestFooTest): .

Finished in 0.066047 seconds.

8 tests, 1 assertions, 0 failures, 0 errors
@@@

Is this a right behavior?</body>
      <body-html>&lt;div&gt;&lt;p&gt;Hmm, test works, but redundant test cases appear out of
nowhere.&lt;br&gt;
I hit this with TestResult, and found this ticket.&lt;/p&gt;
&lt;pre&gt;
&lt;code&gt;$ rake test:units
(in /tmp/foo)
/usr/bin/ruby1.8 -I&quot;lib:test&quot; &quot;/home/nov/gems/gems/rake-0.8.7/lib/rake/rake_test_loader.rb&quot; &quot;test/unit/test_foo_test.rb&quot; 
Loaded suite /home/nov/gems/gems/rake-0.8.7/lib/rake/rake_test_loader
Started
........
Finished in 0.057495 seconds.

8 tests, 1 assertions, 0 failures, 0 errors
^^^^^^^
$ ruby -I test test/unit/test_foo_test.rb -v
Loaded suite test/unit/test_foo_test
Started
test_foos(ActionController::IntegrationTest): .
test_foos(ActionController::TestCase): .
test_foos(ActionMailer::TestCase): .
test_foos(ActionView::TestCase): .
test_foos(ActiveRecord::TestCase): .
test_foos(ActiveSupport::TestCase): .
test_foos(TestFooTest): .
test_the_truth(TestFooTest): .

Finished in 0.066047 seconds.

8 tests, 1 assertions, 0 failures, 0 errors&lt;/code&gt;
&lt;/pre&gt;
&lt;p&gt;Is this a right behavior?&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">true</closed>
      <created-at type="datetime">2009-05-27T07:13:53+01:00</created-at>
      <creator-id type="integer">32378</creator-id>
      <diffable-attributes type="yaml">--- {}

</diffable-attributes>
      <milestone-id type="integer">9903</milestone-id>
      <number type="integer">1708</number>
      <permalink>fixtures-starting-with-test_-will-break-unit-tests</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>invalid</state>
      <tag>2.2.2 actioncontroller exceptions fixtures test testing tests unit</tag>
      <title>Fixtures starting with &quot;test_&quot; will break unit tests</title>
      <updated-at type="datetime">2009-05-27T07:13:59+01:00</updated-at>
      <user-id type="integer">30467</user-id>
      <version type="integer">6</version>
      <user-name>Nobuhiro IMAI</user-name>
      <creator-name>hukl</creator-name>
      <assigned-user-name>Pratik</assigned-user-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/1708</url>
      <milestone-title>2.x</milestone-title>
      <priority-name nil="true"></priority-name>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer">1366</assigned-user-id>
      <attachments-count type="integer">1</attachments-count>
      <body>Patch attached. Does it make sense?</body>
      <body-html>&lt;div&gt;&lt;p&gt;Patch attached. Does it make sense?&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">true</closed>
      <created-at type="datetime">2009-05-30T07:31:30+01:00</created-at>
      <creator-id type="integer">32378</creator-id>
      <diffable-attributes type="yaml">--- 
:tag: 2.2.2 actioncontroller exceptions fixtures test testing tests unit
:title: Fixtures starting with &quot;test_&quot; will break unit tests
</diffable-attributes>
      <milestone-id type="integer">9903</milestone-id>
      <number type="integer">1708</number>
      <permalink>fixtures-starting-with-test_-will-break-unit-tests</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>invalid</state>
      <tag>2.3.2 activerecord fixtures patch test testing tests unit</tag>
      <title>Fixtures starting with &quot;test_&quot; run redundant unit tests</title>
      <updated-at type="datetime">2009-05-30T07:31:36+01:00</updated-at>
      <user-id type="integer">30467</user-id>
      <version type="integer">7</version>
      <user-name>Nobuhiro IMAI</user-name>
      <creator-name>hukl</creator-name>
      <assigned-user-name>Pratik</assigned-user-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/1708</url>
      <milestone-title>2.x</milestone-title>
      <priority-name nil="true"></priority-name>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer">1366</assigned-user-id>
      <attachments-count type="integer">2</attachments-count>
      <body>Closing as requested in #2992.</body>
      <body-html>&lt;div&gt;&lt;p&gt;Closing as requested in &lt;a href=&quot;/projects/8994/tickets/2992&quot;
title=&quot;Ticket #2992&quot;&gt;#2992&lt;/a&gt;.&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">true</closed>
      <created-at type="datetime">2009-08-08T14:39:04+01:00</created-at>
      <creator-id type="integer">32378</creator-id>
      <diffable-attributes type="yaml">--- 
:state: invalid
</diffable-attributes>
      <milestone-id type="integer">9903</milestone-id>
      <number type="integer">1708</number>
      <permalink>fixtures-starting-with-test_-will-break-unit-tests</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>stale</state>
      <tag>2.3.2 activerecord fixtures patch test testing tests unit</tag>
      <title>Fixtures starting with &quot;test_&quot; run redundant unit tests</title>
      <updated-at type="datetime">2009-08-08T14:39:05+01:00</updated-at>
      <user-id type="integer">19965</user-id>
      <version type="integer">8</version>
      <user-name>Jos&#233; Valim</user-name>
      <creator-name>hukl</creator-name>
      <assigned-user-name>Pratik</assigned-user-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/1708</url>
      <milestone-title>2.x</milestone-title>
      <priority-name nil="true"></priority-name>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer">1366</assigned-user-id>
      <attachments-count type="integer">2</attachments-count>
      <body></body>
      <body-html></body-html>
      <closed type="boolean">true</closed>
      <created-at type="datetime">2009-08-08T14:53:45+01:00</created-at>
      <creator-id type="integer">32378</creator-id>
      <diffable-attributes type="yaml">--- 
:state: stale
</diffable-attributes>
      <milestone-id type="integer">9903</milestone-id>
      <number type="integer">1708</number>
      <permalink>fixtures-starting-with-test_-will-break-unit-tests</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>invalid</state>
      <tag>2.3.2 activerecord fixtures patch test testing tests unit</tag>
      <title>Fixtures starting with &quot;test_&quot; run redundant unit tests</title>
      <updated-at type="datetime">2009-08-08T14:53:51+01:00</updated-at>
      <user-id type="integer">19965</user-id>
      <version type="integer">9</version>
      <user-name>Jos&#233; Valim</user-name>
      <creator-name>hukl</creator-name>
      <assigned-user-name>Pratik</assigned-user-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/1708</url>
      <milestone-title>2.x</milestone-title>
      <priority-name nil="true"></priority-name>
    </version>
  </versions>
  <attachments type="array">
    <attachment type="Attachment">
      <code>e021e699aefb2e68fb57790716dd205b70f0c5e5</code>
      <content-type>application/zip</content-type>
      <created-at type="datetime">2009-01-07T17:00:38+00:00</created-at>
      <filename>foo.zip</filename>
      <height type="integer" nil="true"></height>
      <id type="integer">76116</id>
      <size type="integer">98374</size>
      <uploader-id type="integer">32378</uploader-id>
      <width type="integer" nil="true"></width>
      <url>http://rails.lighthouseapp.com/attachments/76116/foo.zip</url>
    </attachment>
    <attachment type="Attachment">
      <code>f66c102e9875858353aeb54bb451f34705c935ad</code>
      <content-type>text/plain</content-type>
      <created-at type="datetime">2009-05-30T07:31:30+01:00</created-at>
      <filename>0001-make-fixture-accessors-private.patch</filename>
      <height type="integer" nil="true"></height>
      <id type="integer">127944</id>
      <size type="integer">1555</size>
      <uploader-id type="integer">30467</uploader-id>
      <width type="integer" nil="true"></width>
      <url>http://rails.lighthouseapp.com/attachments/127944/0001-make-fixture-accessors-private.patch</url>
    </attachment>
  </attachments>
</ticket>
