<?xml version="1.0" encoding="UTF-8"?>
<ticket>
  <assigned-user-id type="integer" nil="true"></assigned-user-id>
  <attachments-count type="integer">0</attachments-count>
  <closed type="boolean">true</closed>
  <created-at type="datetime">2009-12-28T20:48:04+00:00</created-at>
  <creator-id type="integer">76945</creator-id>
  <milestone-due-on type="datetime" nil="true"></milestone-due-on>
  <milestone-id type="integer" nil="true"></milestone-id>
  <number type="integer">3627</number>
  <permalink>attempting-to-add-a-domain-to-zerigo-fails</permalink>
  <priority type="integer">3</priority>
  <project-id type="integer">8994</project-id>
  <raw-data type="binary" nil="true" encoding="base64"></raw-data>
  <state>invalid</state>
  <tag nil="true"></tag>
  <title>INVALID: Attempting to add a domain to Zerigo fails</title>
  <updated-at type="datetime">2010-04-11T04:47:28+01:00</updated-at>
  <user-id type="integer">14998</user-id>
  <version type="integer">5</version>
  <user-name>Ryan Bigg</user-name>
  <creator-name>David Dollar</creator-name>
  <url>http://rails.lighthouseapp.com/projects/8994/tickets/3627</url>
  <priority-name>Low</priority-name>
  <original-body>Adding the Zerigo addon with a domain that already exists on Zerigo gives the following error, but the client only sees &quot;Internal Server Error&quot; so they don't have enough information to know what's failing.

@@@
2009-12-28T12:26:21-08:00 core.12940 core[8492]: RuntimeError processing http://heroku.com/apps/jeffrey-wilcke/domains/
        RuntimeError: Unknown Exception: Domain is already attached to another account
        /mnt/home/core/lib/zerigo_api.rb:341:in `api_error_to_exception'
        /mnt/home/core/lib/zerigo_api.rb:63:in `add_domain'
        /mnt/home/core/app/models/domain_name.rb:293:in `zerigo_dns_update'
        /mnt/home/core/app/models/domain_name.rb:32:in `validate'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/validations.rb:1099:in `valid_without_callbacks?'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/callbacks.rb:315:in `valid?'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/validations.rb:1077:in `save_without_dirty'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/dirty.rb:79:in `save_without_transactions'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:229:in `send'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:229:in `with_transaction_returning_status'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in `transaction'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:182:in `transaction'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:228:in `with_transaction_returning_status'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:196:in `save'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:208:in `rollback_active_record_state!'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:196:in `save'
        /mnt/home/core/app/controllers/domain_names_controller.rb:14:in `add'
        /home/core/vendor/bundler_gems/gems/actionpack-2.3.4/lib/action_controller/mime_responds.rb:106:in `call'
        /home/
@@@</original-body>
  <latest-body>Adding the Zerigo addon with a domain that already exists on Zerigo gives the following error, but the client only sees &quot;Internal Server Error&quot; so they don't have enough information to know what's failing.

@@@
2009-12-28T12:26:21-08:00 core.12940 core[8492]: RuntimeError processing http://heroku.com/apps/jeffrey-wilcke/domains/
        RuntimeError: Unknown Exception: Domain is already attached to another account
        /mnt/home/core/lib/zerigo_api.rb:341:in `api_error_to_exception'
        /mnt/home/core/lib/zerigo_api.rb:63:in `add_domain'
        /mnt/home/core/app/models/domain_name.rb:293:in `zerigo_dns_update'
        /mnt/home/core/app/models/domain_name.rb:32:in `validate'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/validations.rb:1099:in `valid_without_callbacks?'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/callbacks.rb:315:in `valid?'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/validations.rb:1077:in `save_without_dirty'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/dirty.rb:79:in `save_without_transactions'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:229:in `send'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:229:in `with_transaction_returning_status'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in `transaction'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:182:in `transaction'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:228:in `with_transaction_returning_status'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:196:in `save'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:208:in `rollback_active_record_state!'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:196:in `save'
        /mnt/home/core/app/controllers/domain_names_controller.rb:14:in `add'
        /home/core/vendor/bundler_gems/gems/actionpack-2.3.4/lib/action_controller/mime_responds.rb:106:in `call'
        /home/
@@@</latest-body>
  <original-body-html>&lt;div&gt;&lt;p&gt;Adding the Zerigo addon with a domain that already exists on
Zerigo gives the following error, but the client only sees
&quot;Internal Server Error&quot; so they don't have enough information to
know what's failing.&lt;/p&gt;
&lt;pre&gt;
&lt;code&gt;2009-12-28T12:26:21-08:00 core.12940 core[8492]: RuntimeError processing http://heroku.com/apps/jeffrey-wilcke/domains/
        RuntimeError: Unknown Exception: Domain is already attached to another account
        /mnt/home/core/lib/zerigo_api.rb:341:in `api_error_to_exception'
        /mnt/home/core/lib/zerigo_api.rb:63:in `add_domain'
        /mnt/home/core/app/models/domain_name.rb:293:in `zerigo_dns_update'
        /mnt/home/core/app/models/domain_name.rb:32:in `validate'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/validations.rb:1099:in `valid_without_callbacks?'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/callbacks.rb:315:in `valid?'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/validations.rb:1077:in `save_without_dirty'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/dirty.rb:79:in `save_without_transactions'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:229:in `send'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:229:in `with_transaction_returning_status'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in `transaction'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:182:in `transaction'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:228:in `with_transaction_returning_status'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:196:in `save'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:208:in `rollback_active_record_state!'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:196:in `save'
        /mnt/home/core/app/controllers/domain_names_controller.rb:14:in `add'
        /home/core/vendor/bundler_gems/gems/actionpack-2.3.4/lib/action_controller/mime_responds.rb:106:in `call'
        /home/&lt;/code&gt;
&lt;/pre&gt;&lt;/div&gt;</original-body-html>
  <versions type="array">
    <version type="Ticket::Version">
      <assigned-user-id type="integer" nil="true"></assigned-user-id>
      <attachments-count type="integer">0</attachments-count>
      <body>Adding the Zerigo addon with a domain that already exists on Zerigo gives the following error, but the client only sees &quot;Internal Server Error&quot; so they don't have enough information to know what's failing.

@@@
2009-12-28T12:26:21-08:00 core.12940 core[8492]: RuntimeError processing http://heroku.com/apps/jeffrey-wilcke/domains/
        RuntimeError: Unknown Exception: Domain is already attached to another account
        /mnt/home/core/lib/zerigo_api.rb:341:in `api_error_to_exception'
        /mnt/home/core/lib/zerigo_api.rb:63:in `add_domain'
        /mnt/home/core/app/models/domain_name.rb:293:in `zerigo_dns_update'
        /mnt/home/core/app/models/domain_name.rb:32:in `validate'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/validations.rb:1099:in `valid_without_callbacks?'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/callbacks.rb:315:in `valid?'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/validations.rb:1077:in `save_without_dirty'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/dirty.rb:79:in `save_without_transactions'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:229:in `send'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:229:in `with_transaction_returning_status'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in `transaction'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:182:in `transaction'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:228:in `with_transaction_returning_status'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:196:in `save'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:208:in `rollback_active_record_state!'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:196:in `save'
        /mnt/home/core/app/controllers/domain_names_controller.rb:14:in `add'
        /home/core/vendor/bundler_gems/gems/actionpack-2.3.4/lib/action_controller/mime_responds.rb:106:in `call'
        /home/
@@@</body>
      <body-html>&lt;div&gt;&lt;p&gt;Adding the Zerigo addon with a domain that already exists on
Zerigo gives the following error, but the client only sees
&quot;Internal Server Error&quot; so they don't have enough information to
know what's failing.&lt;/p&gt;
&lt;pre&gt;
&lt;code&gt;2009-12-28T12:26:21-08:00 core.12940 core[8492]: RuntimeError processing http://heroku.com/apps/jeffrey-wilcke/domains/
        RuntimeError: Unknown Exception: Domain is already attached to another account
        /mnt/home/core/lib/zerigo_api.rb:341:in `api_error_to_exception'
        /mnt/home/core/lib/zerigo_api.rb:63:in `add_domain'
        /mnt/home/core/app/models/domain_name.rb:293:in `zerigo_dns_update'
        /mnt/home/core/app/models/domain_name.rb:32:in `validate'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/validations.rb:1099:in `valid_without_callbacks?'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/callbacks.rb:315:in `valid?'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/validations.rb:1077:in `save_without_dirty'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/dirty.rb:79:in `save_without_transactions'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:229:in `send'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:229:in `with_transaction_returning_status'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in `transaction'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:182:in `transaction'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:228:in `with_transaction_returning_status'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:196:in `save'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:208:in `rollback_active_record_state!'
        /home/core/vendor/bundler_gems/gems/activerecord-2.3.4/lib/active_record/transactions.rb:196:in `save'
        /mnt/home/core/app/controllers/domain_names_controller.rb:14:in `add'
        /home/core/vendor/bundler_gems/gems/actionpack-2.3.4/lib/action_controller/mime_responds.rb:106:in `call'
        /home/&lt;/code&gt;
&lt;/pre&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">false</closed>
      <created-at type="datetime">2009-12-28T20:48:04+00:00</created-at>
      <creator-id type="integer">76945</creator-id>
      <diffable-attributes type="yaml">--- {}

</diffable-attributes>
      <milestone-id type="integer" nil="true"></milestone-id>
      <number type="integer">3627</number>
      <permalink>attempting-to-add-a-domain-to-zerigo-fails</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>new</state>
      <tag nil="true"></tag>
      <title>Attempting to add a domain to Zerigo fails</title>
      <updated-at type="datetime">2009-12-28T20:48:43+00:00</updated-at>
      <user-id type="integer">76945</user-id>
      <version type="integer">1</version>
      <user-name>David Dollar</user-name>
      <creator-name>David Dollar</creator-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/3627</url>
      <priority-name nil="true"></priority-name>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer">14998</assigned-user-id>
      <attachments-count type="integer">0</attachments-count>
      <body>This is an heroku error, isn't it?</body>
      <body-html>&lt;div&gt;&lt;p&gt;This is an heroku error, isn't it?&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">false</closed>
      <created-at type="datetime">2010-04-11T04:38:49+01:00</created-at>
      <creator-id type="integer">76945</creator-id>
      <diffable-attributes type="yaml">--- 
:assigned_user: 
</diffable-attributes>
      <milestone-id type="integer" nil="true"></milestone-id>
      <number type="integer">3627</number>
      <permalink>attempting-to-add-a-domain-to-zerigo-fails</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>new</state>
      <tag nil="true"></tag>
      <title>Attempting to add a domain to Zerigo fails</title>
      <updated-at type="datetime">2010-04-11T04:38:53+01:00</updated-at>
      <user-id type="integer">22164</user-id>
      <version type="integer">2</version>
      <user-name>Roland Moriz</user-name>
      <creator-name>David Dollar</creator-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/3627</url>
      <priority-name nil="true"></priority-name>
      <assigned-user-name>Ryan Bigg</assigned-user-name>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer" nil="true"></assigned-user-id>
      <attachments-count type="integer">0</attachments-count>
      <body>Yes it is, must have mistakenly posted to the wrong Lighthouse. Sorry!</body>
      <body-html>&lt;div&gt;&lt;p&gt;Yes it is, must have mistakenly posted to the wrong Lighthouse.
Sorry!&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">false</closed>
      <created-at type="datetime">2010-04-11T04:44:20+01:00</created-at>
      <creator-id type="integer">76945</creator-id>
      <diffable-attributes type="yaml">--- 
:assigned_user: 14998
</diffable-attributes>
      <milestone-id type="integer" nil="true"></milestone-id>
      <number type="integer">3627</number>
      <permalink>attempting-to-add-a-domain-to-zerigo-fails</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>new</state>
      <tag nil="true"></tag>
      <title>Attempting to add a domain to Zerigo fails</title>
      <updated-at type="datetime">2010-04-11T04:44:21+01:00</updated-at>
      <user-id type="integer">76945</user-id>
      <version type="integer">3</version>
      <user-name>David Dollar</user-name>
      <creator-name>David Dollar</creator-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/3627</url>
      <priority-name nil="true"></priority-name>
      <assigned-user-name nil="true"></assigned-user-name>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer" nil="true"></assigned-user-id>
      <attachments-count type="integer">0</attachments-count>
      <body></body>
      <body-html></body-html>
      <closed type="boolean">false</closed>
      <created-at type="datetime">2010-04-11T04:45:20+01:00</created-at>
      <creator-id type="integer">76945</creator-id>
      <diffable-attributes type="yaml">--- 
:title: Attempting to add a domain to Zerigo fails
</diffable-attributes>
      <milestone-id type="integer" nil="true"></milestone-id>
      <number type="integer">3627</number>
      <permalink>attempting-to-add-a-domain-to-zerigo-fails</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>new</state>
      <tag nil="true"></tag>
      <title>INVALID: Attempting to add a domain to Zerigo fails</title>
      <updated-at type="datetime">2010-04-11T04:45:21+01:00</updated-at>
      <user-id type="integer">76945</user-id>
      <version type="integer">4</version>
      <user-name>David Dollar</user-name>
      <creator-name>David Dollar</creator-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/3627</url>
      <priority-name nil="true"></priority-name>
      <assigned-user-name nil="true"></assigned-user-name>
    </version>
    <version type="Ticket::Version">
      <assigned-user-id type="integer" nil="true"></assigned-user-id>
      <attachments-count type="integer">0</attachments-count>
      <body>Seems to me like a bug in Zerigo, not here ;)</body>
      <body-html>&lt;div&gt;&lt;p&gt;Seems to me like a bug in Zerigo, not here ;)&lt;/p&gt;&lt;/div&gt;</body-html>
      <closed type="boolean">true</closed>
      <created-at type="datetime">2010-04-11T04:47:28+01:00</created-at>
      <creator-id type="integer">76945</creator-id>
      <diffable-attributes type="yaml">--- 
:state: new
</diffable-attributes>
      <milestone-id type="integer" nil="true"></milestone-id>
      <number type="integer">3627</number>
      <permalink>attempting-to-add-a-domain-to-zerigo-fails</permalink>
      <priority type="integer">0</priority>
      <project-id type="integer">8994</project-id>
      <state>invalid</state>
      <tag nil="true"></tag>
      <title>INVALID: Attempting to add a domain to Zerigo fails</title>
      <updated-at type="datetime">2010-04-11T04:47:28+01:00</updated-at>
      <user-id type="integer">14998</user-id>
      <version type="integer">5</version>
      <user-name>Ryan Bigg</user-name>
      <creator-name>David Dollar</creator-name>
      <url>http://rails.lighthouseapp.com/projects/8994/tickets/3627</url>
      <priority-name nil="true"></priority-name>
      <assigned-user-name nil="true"></assigned-user-name>
    </version>
  </versions>
</ticket>
